# Этап сборки
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

# Копируем файл проекта и восстанавливаем зависимости
COPY ["TestGrand.Api/TestGrand.Api.csproj", "TestGrand.Api/"]
RUN dotnet restore "TestGrand.Api/TestGrand.Api.csproj"

# Копируем все остальное и собираем проект
COPY . .
WORKDIR "/src/TestGrand.Api"
RUN dotnet publish "TestGrand.Api.csproj" -c Release -o /app/publish

# Этап запуска
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
EXPOSE 8080
EXPOSE 443

COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "TestGrand.Api.dll"]